import 'package:excel/excel.dart';
import 'package:file_picker/file_picker.dart';
import '../models/product_model.dart';

class ExcelService {
  Future<List<Product>> importProducts() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['xlsx', 'xls'],
      withData: true, // Need this for Web
    );

    if (result == null || result.files.isEmpty) return [];

    final bytes = result.files.first.bytes;
    if (bytes == null) return [];

    final excel = Excel.decodeBytes(bytes);
    final sheet = excel.tables.keys.first;
    final rows = excel.tables[sheet]!.rows;

    List<Product> importedProducts = [];

    // Assuming first row is header
    for (int i = 1; i < rows.length; i++) {
      final row = rows[i];
      if (row.isEmpty || row[0]?.value == null) continue;

      final name = row[0]?.value.toString() ?? '';
      final priceStr = row[1]?.value.toString() ?? '0';
      double price = double.tryParse(priceStr) ?? 0.0;
      final imageUrl = row.length > 2 ? row[2]?.value?.toString() : null;

      importedProducts.add(
        Product(
          id: '', // Empty ID, will be generated by Firestore
          name: name,
          price: price,
          imageUrl: imageUrl,
        ),
      );
    }
    return importedProducts;
  }
}
