// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFf-df2SZ9hCEG6MVqY_csCmyHkhnsl0',
    appId: '1:958144325653:web:080ba93b6d42b7a8d7461c',
    messagingSenderId: '958144325653',
    projectId: 'store-2703f',
    authDomain: 'store-2703f.firebaseapp.com',
    storageBucket: 'store-2703f.firebasestorage.app',
    measurementId: 'G-H3F2YGY1NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRPH9hA0al2mt6S37CcQhfMlyRDhcnT8E',
    appId: '1:958144325653:android:203927c2c0d20683d7461c',
    messagingSenderId: '958144325653',
    projectId: 'store-2703f',
    storageBucket: 'store-2703f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlOArICUEsz57mf8rkc5U0qgGgmtqAjxM',
    appId: '1:958144325653:ios:441be3d7b43718e5d7461c',
    messagingSenderId: '958144325653',
    projectId: 'store-2703f',
    storageBucket: 'store-2703f.firebasestorage.app',
    iosBundleId: 'com.example.webStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlOArICUEsz57mf8rkc5U0qgGgmtqAjxM',
    appId: '1:958144325653:ios:441be3d7b43718e5d7461c',
    messagingSenderId: '958144325653',
    projectId: 'store-2703f',
    storageBucket: 'store-2703f.firebasestorage.app',
    iosBundleId: 'com.example.webStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRFf-df2SZ9hCEG6MVqY_csCmyHkhnsl0',
    appId: '1:958144325653:web:b1ad53e5a4f5c3c6d7461c',
    messagingSenderId: '958144325653',
    projectId: 'store-2703f',
    authDomain: 'store-2703f.firebaseapp.com',
    storageBucket: 'store-2703f.firebasestorage.app',
    measurementId: 'G-M2WTXYMRNX',
  );
}
